---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all
  roles_path: ../
  requirements_path: test-requirements.ini

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2
    driver_config:
      box: wittman/centos-7.2-ansible

suites:
  - name: default
